### ISSUE TITLE
Still working

### ISSUE THREAD

**Issue by edouardkleinhans** [thomasf/drone-mvn#3]
Hello, 

I try to use this plugin with drone 0.5 and I get error 

panic: EOF 0s
goroutine 1 [running]: 0s
github.com/thomasf/drone-mvn/vendor/github.com/drone/drone-plugin-go/plugin.MustParse() 0s
	/go/src/github.com/thomasf/drone-mvn/vendor/github.com/drone/drone-plugin-go/plugin/param.go:129 +0x59 0s
main.main() 0s
	/go/src/github.com/thomasf/drone-mvn/main.go:52 +0x47c

Any idea ?

**Comment by thomasf** [comment]
It's not ported to 0.5 yet.

I have just started using 0.5 myself but haven't migrated any old build configurations or even looked at api changes yet.
